/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;

/**
 *
 * @author Silvana
 */
public class DialogIntroducirHelado extends javax.swing.JDialog {

    /**
     * Creates new form DialogIntroducirHelado
     */
    public DialogIntroducirHelado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoAlusuario = new javax.swing.JLabel();
        posicionIntroducida = new javax.swing.JTextField();
        textoAlusuario1 = new javax.swing.JLabel();
        saborIntroducido = new javax.swing.JTextField();
        textoAlusuario2 = new javax.swing.JLabel();
        precioIntroducido = new javax.swing.JTextField();
        textoAlusuario3 = new javax.swing.JLabel();
        insertarHelado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tiposHelado = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textoAlusuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoAlusuario.setText("Introduzca la posición del helado");

        posicionIntroducida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                posicionIntroducidaKeyTyped(evt);
            }
        });

        textoAlusuario1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoAlusuario1.setText("Introduzca el sabor del helado");

        textoAlusuario2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoAlusuario2.setText("Introduzca el precio del helado");

        textoAlusuario3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoAlusuario3.setText("Introduzca el tipo del helado");

        insertarHelado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertarHelado.setText("Insertar");
        insertarHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarHeladoActionPerformed(evt);
            }
        });

        tiposHelado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Palo", "Tarrina", "Cucurucho" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(tiposHelado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoAlusuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoAlusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saborIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoAlusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicionIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoAlusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertarHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textoAlusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posicionIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoAlusuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saborIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoAlusuario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoAlusuario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(insertarHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posicionIntroducidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_posicionIntroducidaKeyTyped
        // TODO add your handling code here:
        if (posicionIntroducida.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_posicionIntroducidaKeyTyped

    private void insertarHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarHeladoActionPerformed
        // TODO add your handling code here:
        //Igualar los valores del helado a los datos introducidos.
        //Cerrara la ventana
    }//GEN-LAST:event_insertarHeladoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogIntroducirHelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogIntroducirHelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogIntroducirHelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogIntroducirHelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogIntroducirHelado dialog = new DialogIntroducirHelado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insertarHelado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField posicionIntroducida;
    private javax.swing.JTextField precioIntroducido;
    private javax.swing.JTextField saborIntroducido;
    private javax.swing.JLabel textoAlusuario;
    private javax.swing.JLabel textoAlusuario1;
    private javax.swing.JLabel textoAlusuario2;
    private javax.swing.JLabel textoAlusuario3;
    private javax.swing.JList<String> tiposHelado;
    // End of variables declaration//GEN-END:variables
}
