/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;


/**
 *
 * @author Silvana
 */
public class DialogoEliminarHeladoPosicion extends javax.swing.JDialog {

    /**
     * Creates new form DialogReponerHelado
     */
    public DialogoEliminarHeladoPosicion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.padre = (Exec) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmaciónHelado = new javax.swing.JDialog();
        textoConfirmación = new javax.swing.JLabel();
        botonSi = new javax.swing.JButton();
        botonNo = new javax.swing.JButton();
        textoAlUsuario = new javax.swing.JLabel();
        posicionIntroducida = new javax.swing.JTextField();
        eliminarHelado = new javax.swing.JButton();
        posicionCuatro = new javax.swing.JButton();
        posicionCinco = new javax.swing.JButton();
        posicionSeis = new javax.swing.JButton();
        posicionSiete = new javax.swing.JButton();
        posicionOcho = new javax.swing.JButton();
        posicionNueve = new javax.swing.JButton();
        posicionCero = new javax.swing.JButton();
        posicionUno = new javax.swing.JButton();
        posicionDos = new javax.swing.JButton();
        posicionTres = new javax.swing.JButton();
        borrarPosicion = new javax.swing.JButton();

        confirmaciónHelado.setAlwaysOnTop(true);
        confirmaciónHelado.setModal(true);
        confirmaciónHelado.setResizable(false);

        textoConfirmación.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConfirmación.setText("¿Esta seguro de que quiere eliminar el helado?");

        botonSi.setText("Si");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });

        botonNo.setText("No");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmaciónHeladoLayout = new javax.swing.GroupLayout(confirmaciónHelado.getContentPane());
        confirmaciónHelado.getContentPane().setLayout(confirmaciónHeladoLayout);
        confirmaciónHeladoLayout.setHorizontalGroup(
            confirmaciónHeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaciónHeladoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(botonSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(botonNo)
                .addGap(70, 70, 70))
            .addGroup(confirmaciónHeladoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(textoConfirmación, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmaciónHeladoLayout.setVerticalGroup(
            confirmaciónHeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaciónHeladoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoConfirmación)
                .addGap(18, 18, 18)
                .addGroup(confirmaciónHeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSi)
                    .addComponent(botonNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmaciónHelado.setSize(400, 200);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        textoAlUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoAlUsuario.setText("Introduzca la posición del helado");

        posicionIntroducida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                posicionIntroducidaKeyTyped(evt);
            }
        });

        eliminarHelado.setText("Eliminar");
        eliminarHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarHeladoActionPerformed(evt);
            }
        });

        posicionCuatro.setText("4");
        posicionCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCuatroActionPerformed(evt);
            }
        });

        posicionCinco.setText("5");
        posicionCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCincoActionPerformed(evt);
            }
        });

        posicionSeis.setText("6");
        posicionSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSeisActionPerformed(evt);
            }
        });

        posicionSiete.setText("7");
        posicionSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSieteActionPerformed(evt);
            }
        });

        posicionOcho.setText("8");
        posicionOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionOchoActionPerformed(evt);
            }
        });

        posicionNueve.setText("9");
        posicionNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionNueveActionPerformed(evt);
            }
        });

        posicionCero.setText("0");
        posicionCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCeroActionPerformed(evt);
            }
        });

        posicionUno.setText("1");
        posicionUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionUnoActionPerformed(evt);
            }
        });

        posicionDos.setText("2");
        posicionDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionDosActionPerformed(evt);
            }
        });

        posicionTres.setText("3");
        posicionTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionTresActionPerformed(evt);
            }
        });

        borrarPosicion.setText("Borrar");
        borrarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPosicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(textoAlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(borrarPosicion)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(posicionCinco)
                                .addGap(18, 18, 18)
                                .addComponent(posicionSeis)
                                .addGap(18, 18, 18)
                                .addComponent(posicionSiete)
                                .addGap(18, 18, 18)
                                .addComponent(posicionOcho)
                                .addGap(18, 18, 18)
                                .addComponent(posicionNueve))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(posicionCero)
                                .addGap(18, 18, 18)
                                .addComponent(posicionUno)
                                .addGap(18, 18, 18)
                                .addComponent(posicionDos)
                                .addGap(18, 18, 18)
                                .addComponent(posicionTres)
                                .addGap(18, 18, 18)
                                .addComponent(posicionCuatro))
                            .addComponent(eliminarHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(posicionIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(textoAlUsuario)
                .addGap(18, 18, 18)
                .addComponent(posicionIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(posicionCero)
                            .addComponent(posicionUno)
                            .addComponent(posicionDos)
                            .addComponent(posicionTres)
                            .addComponent(posicionCuatro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(posicionCinco)
                            .addComponent(posicionSeis)
                            .addComponent(posicionSiete)
                            .addComponent(posicionOcho)
                            .addComponent(posicionNueve)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(borrarPosicion)))
                .addGap(18, 18, 18)
                .addComponent(eliminarHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarHeladoActionPerformed
        // TODO add your handling code here:
        //Al darle a reponer el helado se le pedira una confirmación:
        
        //Si el usuario no esta seguro volvera a la ventana de pedir la posición
        if (!posicionIntroducida.getText().isEmpty()) {
            confirmaciónHelado.setVisible(true);
        }
    }//GEN-LAST:event_eliminarHeladoActionPerformed

    private void posicionCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCuatroActionPerformed
        // TODO add your handling code here:
        introducirPosicion("4");
    }//GEN-LAST:event_posicionCuatroActionPerformed

    private void posicionCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCincoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("5");
    }//GEN-LAST:event_posicionCincoActionPerformed

    private void posicionSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSeisActionPerformed
        // TODO add your handling code here:
        introducirPosicion("6");
    }//GEN-LAST:event_posicionSeisActionPerformed

    private void posicionSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSieteActionPerformed
        // TODO add your handling code here:
        introducirPosicion("7");
    }//GEN-LAST:event_posicionSieteActionPerformed

    private void posicionOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionOchoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("8");
    }//GEN-LAST:event_posicionOchoActionPerformed

    private void posicionNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionNueveActionPerformed
        // TODO add your handling code here:
        introducirPosicion("9");
    }//GEN-LAST:event_posicionNueveActionPerformed

    private void posicionCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCeroActionPerformed
        // TODO add your handling code here:
        introducirPosicion("0");
    }//GEN-LAST:event_posicionCeroActionPerformed

    private void posicionUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionUnoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("1");
    }//GEN-LAST:event_posicionUnoActionPerformed

    private void posicionDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionDosActionPerformed
        // TODO add your handling code here:
        introducirPosicion("2");
    }//GEN-LAST:event_posicionDosActionPerformed

    private void posicionTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionTresActionPerformed
        // TODO add your handling code here:
        introducirPosicion("3");
    }//GEN-LAST:event_posicionTresActionPerformed

    private void borrarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPosicionActionPerformed
        // TODO add your handling code here:
        posicionIntroducida.setText("");
    }//GEN-LAST:event_borrarPosicionActionPerformed

    private void posicionIntroducidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_posicionIntroducidaKeyTyped
        // TODO add your handling code here:
        if (posicionIntroducida.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_posicionIntroducidaKeyTyped

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        try {
            // TODO add your handling code here:
            //Eliminar el helado y volver a la venta principal
            this.padre.getMh().eliminarHelado(posicionIntroducida.getText());
            this.padre.rellenarTablaHelados();
            confirmaciónHelado.dispose();
            this.dispose();
        } catch (Exception ex) {
            confirmaciónHelado.dispose();
            padre.ventanaError(ex.toString());
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_botonSiActionPerformed

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        // TODO add your handling code here:
        //Volver atras
        confirmaciónHelado.dispose();
    }//GEN-LAST:event_botonNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoEliminarHeladoPosicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoEliminarHeladoPosicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoEliminarHeladoPosicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoEliminarHeladoPosicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoEliminarHeladoPosicion dialog = new DialogoEliminarHeladoPosicion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void introducirPosicion(String posicion) {
        if (posicionIntroducida.getText().length() < 2) {
            posicionIntroducida.setText(posicionIntroducida.getText() + posicion);
        }
    }
           
    private Exec padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPosicion;
    private javax.swing.JButton botonNo;
    private javax.swing.JButton botonSi;
    private javax.swing.JDialog confirmaciónHelado;
    private javax.swing.JButton eliminarHelado;
    private javax.swing.JButton posicionCero;
    private javax.swing.JButton posicionCinco;
    private javax.swing.JButton posicionCuatro;
    private javax.swing.JButton posicionDos;
    private javax.swing.JTextField posicionIntroducida;
    private javax.swing.JButton posicionNueve;
    private javax.swing.JButton posicionOcho;
    private javax.swing.JButton posicionSeis;
    private javax.swing.JButton posicionSiete;
    private javax.swing.JButton posicionTres;
    private javax.swing.JButton posicionUno;
    private javax.swing.JLabel textoAlUsuario;
    private javax.swing.JLabel textoConfirmación;
    // End of variables declaration//GEN-END:variables
}
