/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;

import com.ejerciciosTrimestre.maquinaHeladosV7.biz.Venta;
import com.ejerciciosTrimestre.maquinaHeladosV7.utils.Utils;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 */
public class DialogInformeVentas extends javax.swing.JDialog {

    /**
     * Creates new form DialogInformeVentas
     */
    public DialogInformeVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.padre = (Exec) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        ventanaIngresosTotales = new javax.swing.JDialog();
        textoIngresosTotales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        txtError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVentas = new javax.swing.JMenu();
        verIngresosTotales = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        ventanaIngresosTotales.setAlwaysOnTop(true);
        ventanaIngresosTotales.setAutoRequestFocus(false);
        ventanaIngresosTotales.setModal(true);
        ventanaIngresosTotales.setResizable(false);

        textoIngresosTotales.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout ventanaIngresosTotalesLayout = new javax.swing.GroupLayout(ventanaIngresosTotales.getContentPane());
        ventanaIngresosTotales.getContentPane().setLayout(ventanaIngresosTotalesLayout);
        ventanaIngresosTotalesLayout.setHorizontalGroup(
            ventanaIngresosTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaIngresosTotalesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(textoIngresosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        ventanaIngresosTotalesLayout.setVerticalGroup(
            ventanaIngresosTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaIngresosTotalesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(textoIngresosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        ventanaIngresosTotales.setSize(400, 100);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha y hora", "Posición", "Sabor", "Precio", "Tipo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        // Set the renderer for the first column to center the text
        tablaVentas.setColumnSelectionAllowed(true);
        tablaVentas.setFillsViewportHeight(true);
        tablaVentas.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tablaVentas.setShowVerticalLines(true);
        tablaVentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaVentas);
        tablaVentas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablaVentas.getColumnModel().getColumnCount() > 0) {
            tablaVentas.getColumnModel().getColumn(0).setResizable(false);
            tablaVentas.getColumnModel().getColumn(1).setResizable(false);
            tablaVentas.getColumnModel().getColumn(2).setResizable(false);
            tablaVentas.getColumnModel().getColumn(3).setResizable(false);
            tablaVentas.getColumnModel().getColumn(4).setResizable(false);
            tablaVentas.getColumnModel().getColumn(5).setResizable(false);
        }
        tablaVentas.getAccessibleContext().setAccessibleName("");

        menuVentas.setText("Menú");

        verIngresosTotales.setText("Ver ingresos totales");
        verIngresosTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verIngresosTotalesActionPerformed(evt);
            }
        });
        menuVentas.add(verIngresosTotales);

        jMenuBar1.add(menuVentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        txtError.setVisible(false);
        ArrayList<Venta> listaVentas;
        DefaultTableModel m = (DefaultTableModel) this.tablaVentas.getModel();
        m.setRowCount(0);
        try {
            listaVentas = padre.getMh().getVentas();
            for (Venta v : listaVentas) {
                Object[] tmp = {v.getFechaHora(), v.getPosicion(), v.getNombre(), Utils.formatoDecimal(v.getPrecio()) + "€", v.getTipo(), v.getCantidad()};
                m.addRow(tmp);
            }
        } catch (Exception ex) {
            this.padre.ventanaError("Ha ocurrido un error al mostrar las ventas");
        }
    }//GEN-LAST:event_formComponentShown

    private void verIngresosTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verIngresosTotalesActionPerformed
        // TODO add your handling code here:
        try {
            textoIngresosTotales.setText("Los ingresos totales son: " + Utils.formatoDecimal(this.padre.getMh().getDineroRecaudado()) + "€");
            ventanaIngresosTotales.setVisible(true);
        } catch (Exception ex) {
            padre.ventanaError(ex.toString());
        }
    }//GEN-LAST:event_verIngresosTotalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogInformeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogInformeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogInformeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogInformeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogInformeVentas dialog = new DialogInformeVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private Exec padre;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JLabel textoIngresosTotales;
    private javax.swing.JLabel txtError;
    private javax.swing.JDialog ventanaIngresosTotales;
    private javax.swing.JMenuItem verIngresosTotales;
    // End of variables declaration//GEN-END:variables

}
