/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;

/**
 *
 * @author gilso
 */
public class DialogCambiarDatos extends javax.swing.JDialog {

    /**
     * Creates new form DialogCambiarDatos
     */
    public DialogCambiarDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.padre = (Exec) parent;
        initComponents();
        setBounds(500, 250, 300, 350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInsertarModificaciones = new javax.swing.JButton();
        labelPsocionHelado = new java.awt.Label();
        jTextPosicionHelado = new java.awt.TextField();
        labelSaborHealdo = new java.awt.Label();
        jTexttSaborHelado = new java.awt.TextField();
        labelPrecioHealdo = new java.awt.Label();
        jTexttPrecioHelado = new java.awt.TextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonInsertarModificaciones.setText("Modificar");
        jButtonInsertarModificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarModificacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertarModificaciones);
        jButtonInsertarModificaciones.setBounds(87, 269, 81, 23);

        labelPsocionHelado.setText("Introduzca la posicion del helado");
        getContentPane().add(labelPsocionHelado);
        labelPsocionHelado.setBounds(31, 34, 184, 20);

        jTextPosicionHelado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPosicionHeladoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextPosicionHelado);
        jTextPosicionHelado.setBounds(31, 64, 82, 20);

        labelSaborHealdo.setText("Introduzca el nuevo sabor del helado");
        getContentPane().add(labelSaborHealdo);
        labelSaborHealdo.setBounds(31, 103, 205, 20);
        getContentPane().add(jTexttSaborHelado);
        jTexttSaborHelado.setBounds(31, 133, 206, 20);

        labelPrecioHealdo.setText("Introduzca el nuevo precio del helado");
        getContentPane().add(labelPrecioHealdo);
        labelPrecioHealdo.setBounds(31, 172, 207, 20);
        getContentPane().add(jTexttPrecioHelado);
        jTexttPrecioHelado.setBounds(31, 202, 206, 20);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/metal.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(-13, -14, 380, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPosicionHeladoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPosicionHeladoKeyTyped
        // TODO add your handling code here:
        if (jTextPosicionHelado.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextPosicionHeladoKeyTyped

    private void jButtonInsertarModificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarModificacionesActionPerformed
        // TODO add your handling code here:
        try {
            if (!jTexttPrecioHelado.getText().isEmpty()) {
                this.padre.getMh().changeSaborOrPrecioByPosicion(jTextPosicionHelado.getText(), jTexttSaborHelado.getText(), Double.parseDouble(jTexttPrecioHelado.getText()));
            } else {
                this.padre.getMh().changeSaborOrPrecioByPosicion(jTextPosicionHelado.getText(), jTexttSaborHelado.getText(), 0);
            }
            this.padre.rellenarTablaHelados();
            this.dispose();
        } catch (Exception ex) {
            this.padre.ventanaError(ex.toString());
        }
    }//GEN-LAST:event_jButtonInsertarModificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCambiarDatos dialog = new DialogCambiarDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private Exec padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonInsertarModificaciones;
    private java.awt.TextField jTextPosicionHelado;
    private java.awt.TextField jTexttPrecioHelado;
    private java.awt.TextField jTexttSaborHelado;
    private java.awt.Label labelPrecioHealdo;
    private java.awt.Label labelPsocionHelado;
    private java.awt.Label labelSaborHealdo;
    // End of variables declaration//GEN-END:variables
}
