/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;

/**
 *
 * @author Silvana
 */
public class DialogReponerHelado extends javax.swing.JDialog {

    /**
     * Creates new form DialogReponerHelado
     */
    public DialogReponerHelado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmaciónHelado = new javax.swing.JDialog();
        textoConfirmación = new javax.swing.JLabel();
        botonSi = new javax.swing.JButton();
        botonNo = new javax.swing.JButton();
        textoAlUsuario = new javax.swing.JLabel();
        posicionIntroducida = new javax.swing.JTextField();
        reponerHelado = new javax.swing.JButton();
        posicionCuatro = new javax.swing.JButton();
        posicionCinco = new javax.swing.JButton();
        posicionSeis = new javax.swing.JButton();
        posicionSiete = new javax.swing.JButton();
        posicionOcho = new javax.swing.JButton();
        posicionNueve = new javax.swing.JButton();
        posicionCero = new javax.swing.JButton();
        posicionUno = new javax.swing.JButton();
        posicionDos = new javax.swing.JButton();
        posicionTres = new javax.swing.JButton();
        borrarPosicion = new javax.swing.JButton();

        textoConfirmación.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConfirmación.setText("¿Esta seguro de que quiere reponer el helado?");

        botonSi.setText("Si");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });

        botonNo.setText("No");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmaciónHeladoLayout = new javax.swing.GroupLayout(confirmaciónHelado.getContentPane());
        confirmaciónHelado.getContentPane().setLayout(confirmaciónHeladoLayout);
        confirmaciónHeladoLayout.setHorizontalGroup(
            confirmaciónHeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaciónHeladoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(botonSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonNo)
                .addGap(70, 70, 70))
            .addGroup(confirmaciónHeladoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(textoConfirmación, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        confirmaciónHeladoLayout.setVerticalGroup(
            confirmaciónHeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaciónHeladoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoConfirmación)
                .addGap(18, 18, 18)
                .addGroup(confirmaciónHeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSi)
                    .addComponent(botonNo))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textoAlUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoAlUsuario.setText("Introduzca la posición del helado");

        posicionIntroducida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                posicionIntroducidaKeyTyped(evt);
            }
        });

        reponerHelado.setText("Reponer");
        reponerHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponerHeladoActionPerformed(evt);
            }
        });

        posicionCuatro.setText("4");
        posicionCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCuatroActionPerformed(evt);
            }
        });

        posicionCinco.setText("5");
        posicionCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCincoActionPerformed(evt);
            }
        });

        posicionSeis.setText("6");
        posicionSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSeisActionPerformed(evt);
            }
        });

        posicionSiete.setText("7");
        posicionSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSieteActionPerformed(evt);
            }
        });

        posicionOcho.setText("8");
        posicionOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionOchoActionPerformed(evt);
            }
        });

        posicionNueve.setText("9");
        posicionNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionNueveActionPerformed(evt);
            }
        });

        posicionCero.setText("0");
        posicionCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCeroActionPerformed(evt);
            }
        });

        posicionUno.setText("1");
        posicionUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionUnoActionPerformed(evt);
            }
        });

        posicionDos.setText("2");
        posicionDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionDosActionPerformed(evt);
            }
        });

        posicionTres.setText("3");
        posicionTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionTresActionPerformed(evt);
            }
        });

        borrarPosicion.setText("Borrar");
        borrarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPosicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reponerHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoAlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(posicionIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(borrarPosicion)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(posicionCinco)
                                            .addGap(18, 18, 18)
                                            .addComponent(posicionSeis)
                                            .addGap(18, 18, 18)
                                            .addComponent(posicionSiete)
                                            .addGap(18, 18, 18)
                                            .addComponent(posicionOcho)
                                            .addGap(18, 18, 18)
                                            .addComponent(posicionNueve))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(posicionCero)
                                            .addGap(18, 18, 18)
                                            .addComponent(posicionUno)
                                            .addGap(18, 18, 18)
                                            .addComponent(posicionDos)
                                            .addGap(18, 18, 18)
                                            .addComponent(posicionTres)
                                            .addGap(18, 18, 18)
                                            .addComponent(posicionCuatro))))))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(textoAlUsuario)
                .addGap(18, 18, 18)
                .addComponent(posicionIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(posicionCero)
                            .addComponent(posicionUno)
                            .addComponent(posicionDos)
                            .addComponent(posicionTres)
                            .addComponent(posicionCuatro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(posicionCinco)
                            .addComponent(posicionSeis)
                            .addComponent(posicionSiete)
                            .addComponent(posicionOcho)
                            .addComponent(posicionNueve)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(borrarPosicion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(reponerHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reponerHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponerHeladoActionPerformed
        // TODO add your handling code here:
        //Al darle a reponer el helado se le pedira una confirmación:
        //Si el usuario esta seguro se repondra el stock del helado
        //Si el usuario no esta seguro volvera a la ventana de pedir la posición
    }//GEN-LAST:event_reponerHeladoActionPerformed

    private void posicionCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCuatroActionPerformed
        // TODO add your handling code here:
        introducirPosicion("4");
    }//GEN-LAST:event_posicionCuatroActionPerformed

    private void posicionCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCincoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("5");
    }//GEN-LAST:event_posicionCincoActionPerformed

    private void posicionSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSeisActionPerformed
        // TODO add your handling code here:
        introducirPosicion("6");
    }//GEN-LAST:event_posicionSeisActionPerformed

    private void posicionSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSieteActionPerformed
        // TODO add your handling code here:
        introducirPosicion("7");
    }//GEN-LAST:event_posicionSieteActionPerformed

    private void posicionOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionOchoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("8");
    }//GEN-LAST:event_posicionOchoActionPerformed

    private void posicionNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionNueveActionPerformed
        // TODO add your handling code here:
        introducirPosicion("9");
    }//GEN-LAST:event_posicionNueveActionPerformed

    private void posicionCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCeroActionPerformed
        // TODO add your handling code here:
        introducirPosicion("0");
    }//GEN-LAST:event_posicionCeroActionPerformed

    private void posicionUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionUnoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("1");
    }//GEN-LAST:event_posicionUnoActionPerformed

    private void posicionDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionDosActionPerformed
        // TODO add your handling code here:
        introducirPosicion("2");
    }//GEN-LAST:event_posicionDosActionPerformed

    private void posicionTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionTresActionPerformed
        // TODO add your handling code here:
        introducirPosicion("3");
    }//GEN-LAST:event_posicionTresActionPerformed

    private void borrarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPosicionActionPerformed
        // TODO add your handling code here:
        posicionIntroducida.setText("");
    }//GEN-LAST:event_borrarPosicionActionPerformed

    private void posicionIntroducidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_posicionIntroducidaKeyTyped
        // TODO add your handling code here:
        if (posicionIntroducida.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_posicionIntroducidaKeyTyped

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        // TODO add your handling code here:
        //Reponer el helado y volver a la venta principal
        //Controlar excepciones
    }//GEN-LAST:event_botonSiActionPerformed

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        // TODO add your handling code here:
        //Volver atras
    }//GEN-LAST:event_botonNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogReponerHelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogReponerHelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogReponerHelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogReponerHelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogReponerHelado dialog = new DialogReponerHelado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void introducirPosicion(String posicion) {
        if (posicionIntroducida.getText().length() < 2) {
            posicionIntroducida.setText(posicionIntroducida.getText() + posicion);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPosicion;
    private javax.swing.JButton botonNo;
    private javax.swing.JButton botonSi;
    private javax.swing.JDialog confirmaciónHelado;
    private javax.swing.JButton posicionCero;
    private javax.swing.JButton posicionCinco;
    private javax.swing.JButton posicionCuatro;
    private javax.swing.JButton posicionDos;
    private javax.swing.JTextField posicionIntroducida;
    private javax.swing.JButton posicionNueve;
    private javax.swing.JButton posicionOcho;
    private javax.swing.JButton posicionSeis;
    private javax.swing.JButton posicionSiete;
    private javax.swing.JButton posicionTres;
    private javax.swing.JButton posicionUno;
    private javax.swing.JButton reponerHelado;
    private javax.swing.JLabel textoAlUsuario;
    private javax.swing.JLabel textoConfirmación;
    // End of variables declaration//GEN-END:variables
}
