/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;

import com.ejerciciosTrimestre.maquinaHeladosV7.utils.Utils;

/**
 *
 * @author dev
 */
public class DialogMonedas extends javax.swing.JDialog {

    /**
     * Creates new form DialogMonedas
     */
    public DialogMonedas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.padre = (Exec) parent;
        initComponents();
        setBounds(750, 350, 340, 240);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verCantidadIntroducida = new javax.swing.JTextField();
        unCentimo = new javax.swing.JButton();
        dosCentimos = new javax.swing.JButton();
        cincoCentimos = new javax.swing.JButton();
        diezCentimos = new javax.swing.JButton();
        veinteCentimos = new javax.swing.JButton();
        cincuentaCentimos = new javax.swing.JButton();
        unEuro = new javax.swing.JButton();
        dosEuros = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(null);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        verCantidadIntroducida.setEditable(false);
        verCantidadIntroducida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        verCantidadIntroducida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verCantidadIntroducida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verCantidadIntroducida.setFocusable(false);
        getContentPane().add(verCantidadIntroducida);
        verCantidadIntroducida.setBounds(40, 10, 250, 32);

        unCentimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/unCentimo.png"))); // NOI18N
        unCentimo.setToolTipText("");
        unCentimo.setContentAreaFilled(false);
        unCentimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unCentimoActionPerformed(evt);
            }
        });
        getContentPane().add(unCentimo);
        unCentimo.setBounds(33, 56, 56, 57);

        dosCentimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/dosCentimos.png"))); // NOI18N
        dosCentimos.setContentAreaFilled(false);
        dosCentimos.setDefaultCapable(false);
        dosCentimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosCentimosActionPerformed(evt);
            }
        });
        getContentPane().add(dosCentimos);
        dosCentimos.setBounds(107, 56, 56, 57);

        cincoCentimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/cincoCentimos.png"))); // NOI18N
        cincoCentimos.setContentAreaFilled(false);
        cincoCentimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoCentimosActionPerformed(evt);
            }
        });
        getContentPane().add(cincoCentimos);
        cincoCentimos.setBounds(181, 56, 56, 57);

        diezCentimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/diezCentimos.png"))); // NOI18N
        diezCentimos.setContentAreaFilled(false);
        diezCentimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diezCentimosActionPerformed(evt);
            }
        });
        getContentPane().add(diezCentimos);
        diezCentimos.setBounds(258, 56, 56, 57);

        veinteCentimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/veinteCentimos.png"))); // NOI18N
        veinteCentimos.setContentAreaFilled(false);
        veinteCentimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veinteCentimosActionPerformed(evt);
            }
        });
        getContentPane().add(veinteCentimos);
        veinteCentimos.setBounds(33, 131, 56, 57);

        cincuentaCentimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/cincuentaCentimos.png"))); // NOI18N
        cincuentaCentimos.setContentAreaFilled(false);
        cincuentaCentimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincuentaCentimosActionPerformed(evt);
            }
        });
        getContentPane().add(cincuentaCentimos);
        cincuentaCentimos.setBounds(107, 131, 56, 57);

        unEuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/unEuro.png"))); // NOI18N
        unEuro.setContentAreaFilled(false);
        unEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unEuroActionPerformed(evt);
            }
        });
        getContentPane().add(unEuro);
        unEuro.setBounds(181, 131, 59, 57);

        dosEuros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/dosEuros.png"))); // NOI18N
        dosEuros.setContentAreaFilled(false);
        dosEuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosEurosActionPerformed(evt);
            }
        });
        getContentPane().add(dosEuros);
        dosEuros.setBounds(258, 131, 56, 57);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/metal.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(-13, -4, 430, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unCentimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unCentimoActionPerformed
        // TODO add your handling code here:
        sumarCantidad(0.01);
    }//GEN-LAST:event_unCentimoActionPerformed

    private void dosCentimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosCentimosActionPerformed
        // TODO add your handling code here:
        sumarCantidad(0.02);
    }//GEN-LAST:event_dosCentimosActionPerformed

    private void cincoCentimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoCentimosActionPerformed
        // TODO add your handling code here:
        sumarCantidad(0.05);
    }//GEN-LAST:event_cincoCentimosActionPerformed

    private void diezCentimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diezCentimosActionPerformed
        // TODO add your handling code here:
        sumarCantidad(0.10);
    }//GEN-LAST:event_diezCentimosActionPerformed

    private void veinteCentimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veinteCentimosActionPerformed
        // TODO add your handling code here:
        sumarCantidad(0.20);
    }//GEN-LAST:event_veinteCentimosActionPerformed

    private void cincuentaCentimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincuentaCentimosActionPerformed
        // TODO add your handling code here:
        sumarCantidad(0.50);
    }//GEN-LAST:event_cincuentaCentimosActionPerformed

    private void unEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unEuroActionPerformed
        // TODO add your handling code here:
        sumarCantidad(1);
    }//GEN-LAST:event_unEuroActionPerformed

    private void dosEurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosEurosActionPerformed
        // TODO add your handling code here:
        sumarCantidad(2);
    }//GEN-LAST:event_dosEurosActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        this.verCantidadIntroducida.setText(Utils.formatoDecimal(this.padre.getMh().getMonedero()) + "€");
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogMonedas dialog = new DialogMonedas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void sumarCantidad(double cantidad) {
        cantidad += padre.getMh().getMonedero();
        padre.getMh().setMonedero(Utils.redondearDecimales(cantidad));
        verCantidadIntroducida.setText(Utils.formatoDecimal(this.padre.getMh().getMonedero()) + "€");
        padre.refreshVerMonedero();
    }
    
    private Exec padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cincoCentimos;
    private javax.swing.JButton cincuentaCentimos;
    private javax.swing.JButton diezCentimos;
    private javax.swing.JButton dosCentimos;
    private javax.swing.JButton dosEuros;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton unCentimo;
    private javax.swing.JButton unEuro;
    private javax.swing.JButton veinteCentimos;
    private javax.swing.JTextField verCantidadIntroducida;
    // End of variables declaration//GEN-END:variables
}
