/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;

import com.ejerciciosTrimestre.maquinaHeladosV7.biz.Helado;
import com.ejerciciosTrimestre.maquinaHeladosV7.biz.MaquinaHelados;
import com.ejerciciosTrimestre.maquinaHeladosV7.exceptions.NotEnoughMoneyException;
import com.ejerciciosTrimestre.maquinaHeladosV7.exceptions.NotValidPositionException;
import com.ejerciciosTrimestre.maquinaHeladosV7.exceptions.QuantityExceededException;
import com.ejerciciosTrimestre.maquinaHeladosV7.utils.Utils;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 *
 */
public class Exec extends javax.swing.JFrame {

    /**
     * Creates new form Exec
     */
    public Exec() {
        initComponents();
        //No permite cerrar la ventana
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devuelto = new javax.swing.JDialog();
        txtUser = new javax.swing.JLabel();
        heladoDevuelto = new javax.swing.JDialog();
        txtHelado = new javax.swing.JLabel();
        txtCambio = new javax.swing.JLabel();
        tipoHelado = new javax.swing.JLabel();
        ventanaError = new javax.swing.JDialog();
        mensajeError = new javax.swing.JLabel();
        masMenosVendido = new javax.swing.JDialog();
        mostrarHeladoMasMenos = new javax.swing.JLabel();
        jButtonMasVendido = new javax.swing.JButton();
        jButtonMenosVendido = new javax.swing.JButton();
        introducirMonedas = new javax.swing.JButton();
        devolverDinero = new javax.swing.JButton();
        verMonedero = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaHelados = new javax.swing.JTable();
        verPosicion = new javax.swing.JTextField();
        posicionDos = new javax.swing.JButton();
        posicionTres = new javax.swing.JButton();
        borrarPosicion = new javax.swing.JButton();
        posicionCuatro = new javax.swing.JButton();
        posicionCinco = new javax.swing.JButton();
        posicionSeis = new javax.swing.JButton();
        posicionSiete = new javax.swing.JButton();
        posicionOcho = new javax.swing.JButton();
        posicionNueve = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        posicionCero = new javax.swing.JButton();
        posicionUno = new javax.swing.JButton();
        pedirHelado = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        informeVentas = new javax.swing.JMenuItem();
        heladosOrderPrecio = new javax.swing.JMenuItem();
        jMenuReponerHelado = new javax.swing.JMenuItem();
        jMenuInsertarHelado = new javax.swing.JMenuItem();
        jMenuHeladoMasVendido = new javax.swing.JMenuItem();
        eliminarHeladoPosicionMenu = new javax.swing.JMenuItem();
        jMenuCambiarDatos = new javax.swing.JMenuItem();

        devuelto.setResizable(false);

        txtUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout devueltoLayout = new javax.swing.GroupLayout(devuelto.getContentPane());
        devuelto.getContentPane().setLayout(devueltoLayout);
        devueltoLayout.setHorizontalGroup(
            devueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devueltoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        devueltoLayout.setVerticalGroup(
            devueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devueltoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        devuelto.setSize(500, 100);

        heladoDevuelto.setResizable(false);

        txtHelado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtCambio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tipoHelado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout heladoDevueltoLayout = new javax.swing.GroupLayout(heladoDevuelto.getContentPane());
        heladoDevuelto.getContentPane().setLayout(heladoDevueltoLayout);
        heladoDevueltoLayout.setHorizontalGroup(
            heladoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heladoDevueltoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(heladoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(heladoDevueltoLayout.createSequentialGroup()
                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(heladoDevueltoLayout.createSequentialGroup()
                        .addComponent(txtHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        heladoDevueltoLayout.setVerticalGroup(
            heladoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heladoDevueltoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(heladoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        heladoDevuelto.setSize(800, 220);

        ventanaError.setModal(true);

        mensajeError.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout ventanaErrorLayout = new javax.swing.GroupLayout(ventanaError.getContentPane());
        ventanaError.getContentPane().setLayout(ventanaErrorLayout);
        ventanaErrorLayout.setHorizontalGroup(
            ventanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaErrorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mensajeError)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        ventanaErrorLayout.setVerticalGroup(
            ventanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaErrorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(mensajeError)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        ventanaError.setSize(500, 200);

        masMenosVendido.setMinimumSize(new java.awt.Dimension(646, 208));

        jButtonMasVendido.setText("Mas Vendido");
        jButtonMasVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasVendidoActionPerformed(evt);
            }
        });

        jButtonMenosVendido.setText("Menos Vendido");
        jButtonMenosVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosVendidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout masMenosVendidoLayout = new javax.swing.GroupLayout(masMenosVendido.getContentPane());
        masMenosVendido.getContentPane().setLayout(masMenosVendidoLayout);
        masMenosVendidoLayout.setHorizontalGroup(
            masMenosVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masMenosVendidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrarHeladoMasMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(masMenosVendidoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButtonMasVendido)
                .addGap(100, 100, 100)
                .addComponent(jButtonMenosVendido)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        masMenosVendidoLayout.setVerticalGroup(
            masMenosVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masMenosVendidoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(mostrarHeladoMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(masMenosVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMasVendido)
                    .addComponent(jButtonMenosVendido))
                .addGap(56, 56, 56))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        introducirMonedas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        introducirMonedas.setText("Introducir monedas");
        introducirMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirMonedasActionPerformed(evt);
            }
        });

        devolverDinero.setBackground(new java.awt.Color(255, 0, 0));
        devolverDinero.setForeground(new java.awt.Color(255, 255, 255));
        devolverDinero.setText("Devolucion");
        devolverDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverDineroActionPerformed(evt);
            }
        });

        verMonedero.setEditable(false);
        verMonedero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        verMonedero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verMonedero.setFocusable(false);

        tablaHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Sabor", "Tipo", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHelados.setColumnSelectionAllowed(true);
        tablaHelados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaHelados.setShowGrid(false);
        tablaHelados.setShowHorizontalLines(true);
        tablaHelados.setShowVerticalLines(true);
        tablaHelados.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaHelados);
        tablaHelados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablaHelados.getColumnModel().getColumnCount() > 0) {
            tablaHelados.getColumnModel().getColumn(0).setResizable(false);
            tablaHelados.getColumnModel().getColumn(1).setResizable(false);
            tablaHelados.getColumnModel().getColumn(2).setResizable(false);
            tablaHelados.getColumnModel().getColumn(3).setResizable(false);
            tablaHelados.getColumnModel().getColumn(4).setResizable(false);
        }

        verPosicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        verPosicion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verPosicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verPosicionKeyTyped(evt);
            }
        });

        posicionDos.setText("2");
        posicionDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionDosActionPerformed(evt);
            }
        });

        posicionTres.setText("3");
        posicionTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionTresActionPerformed(evt);
            }
        });

        borrarPosicion.setBackground(new java.awt.Color(255, 0, 0));
        borrarPosicion.setForeground(new java.awt.Color(255, 255, 255));
        borrarPosicion.setText("Borrar");
        borrarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPosicionActionPerformed(evt);
            }
        });

        posicionCuatro.setText("4");
        posicionCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCuatroActionPerformed(evt);
            }
        });

        posicionCinco.setText("5");
        posicionCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCincoActionPerformed(evt);
            }
        });

        posicionSeis.setText("6");
        posicionSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSeisActionPerformed(evt);
            }
        });

        posicionSiete.setText("7");
        posicionSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSieteActionPerformed(evt);
            }
        });

        posicionOcho.setText("8");
        posicionOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionOchoActionPerformed(evt);
            }
        });

        posicionNueve.setText("9");
        posicionNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionNueveActionPerformed(evt);
            }
        });

        posicionCero.setText("0");
        posicionCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCeroActionPerformed(evt);
            }
        });

        posicionUno.setText("1");
        posicionUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionUnoActionPerformed(evt);
            }
        });

        pedirHelado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        pedirHelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/carritoCompra.png"))); // NOI18N
        pedirHelado.setText("Pedir helado      ");
        pedirHelado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pedirHelado.setIconTextGap(5);
        pedirHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirHeladoActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        informeVentas.setText("Informe de ventas");
        informeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeVentasActionPerformed(evt);
            }
        });
        jMenu1.add(informeVentas);

        heladosOrderPrecio.setText("Ver helados ordenados por precio");
        heladosOrderPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heladosOrderPrecioActionPerformed(evt);
            }
        });
        jMenu1.add(heladosOrderPrecio);

        jMenuReponerHelado.setText("Reponer helado");
        jMenuReponerHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReponerHeladoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuReponerHelado);

        jMenuInsertarHelado.setText("Insertar nuevo helado");
        jMenuInsertarHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInsertarHeladoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuInsertarHelado);

        jMenuHeladoMasVendido.setText("Helados mas y menos vendidos");
        jMenuHeladoMasVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHeladoMasVendidoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuHeladoMasVendido);

        eliminarHeladoPosicionMenu.setText("Eliminar helado");
        eliminarHeladoPosicionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarHeladoPosicionMenuActionPerformed(evt);
            }
        });
        jMenu1.add(eliminarHeladoPosicionMenu);

        jMenuCambiarDatos.setText("Cambiar datos");
        jMenuCambiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCambiarDatosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCambiarDatos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(verMonedero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(devolverDinero)
                        .addGap(18, 18, 18)
                        .addComponent(introducirMonedas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(pedirHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(verPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borrarPosicion)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posicionCero)
                            .addComponent(posicionCinco))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posicionUno)
                            .addComponent(posicionSeis))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posicionDos)
                            .addComponent(posicionSiete))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posicionTres)
                            .addComponent(posicionOcho))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posicionCuatro)
                            .addComponent(posicionNueve))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verMonedero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(devolverDinero)
                            .addComponent(introducirMonedas))))
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pedirHelado)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(verPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(borrarPosicion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posicionCero)
                        .addGap(18, 18, 18)
                        .addComponent(posicionCinco))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posicionUno)
                        .addGap(18, 18, 18)
                        .addComponent(posicionSeis))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posicionDos)
                        .addGap(18, 18, 18)
                        .addComponent(posicionSiete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posicionTres)
                        .addGap(18, 18, 18)
                        .addComponent(posicionOcho))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posicionCuatro)
                        .addGap(18, 18, 18)
                        .addComponent(posicionNueve)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introducirMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirMonedasActionPerformed
        // TODO add your handling code here:
        // TODO hacer que la ventana actualice el monedero en tiempo real:
        DialogMonedas dm = new DialogMonedas(this, true);
        dm.setVisible(true);
        refreshVerMonedero();
    }//GEN-LAST:event_introducirMonedasActionPerformed


    private void devolverDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverDineroActionPerformed
        // TODO add your handling code here:
        if (mh.getMonedero() > 0) {
            devuelto.setVisible(true);
            txtUser.setText("Su dinero le ha sido duevuelto " + Utils.formatoDecimal(mh.getMonedero()) + "€");
            mh.setMonedero(0);
            refreshVerMonedero();
        }
    }//GEN-LAST:event_devolverDineroActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        refreshVerMonedero();
        rellenarTablaHelados();
    }//GEN-LAST:event_formComponentShown

    private void verPosicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verPosicionKeyTyped
        // TODO add your handling code here:
        if (verPosicion.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_verPosicionKeyTyped

    private void posicionDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionDosActionPerformed
        // TODO add your handling code here:
        introducirPosicion("2");
    }//GEN-LAST:event_posicionDosActionPerformed

    private void posicionTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionTresActionPerformed
        // TODO add your handling code here:
        introducirPosicion("3");
    }//GEN-LAST:event_posicionTresActionPerformed

    private void borrarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPosicionActionPerformed
        // TODO add your handling code here:
        verPosicion.setText("");
    }//GEN-LAST:event_borrarPosicionActionPerformed

    private void posicionCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCuatroActionPerformed
        // TODO add your handling code here:
        introducirPosicion("4");
    }//GEN-LAST:event_posicionCuatroActionPerformed

    private void posicionCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCincoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("5");
    }//GEN-LAST:event_posicionCincoActionPerformed

    private void posicionSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSeisActionPerformed
        // TODO add your handling code here:
        introducirPosicion("6");
    }//GEN-LAST:event_posicionSeisActionPerformed

    private void posicionSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSieteActionPerformed
        // TODO add your handling code here:
        introducirPosicion("7");
    }//GEN-LAST:event_posicionSieteActionPerformed

    private void posicionOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionOchoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("8");
    }//GEN-LAST:event_posicionOchoActionPerformed

    private void posicionNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionNueveActionPerformed
        // TODO add your handling code here:
        introducirPosicion("9");
    }//GEN-LAST:event_posicionNueveActionPerformed

    private void posicionCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCeroActionPerformed
        // TODO add your handling code here:
        introducirPosicion("0");
    }//GEN-LAST:event_posicionCeroActionPerformed

    private void posicionUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionUnoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("1");
    }//GEN-LAST:event_posicionUnoActionPerformed

    private void pedirHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirHeladoActionPerformed
        String posicion = verPosicion.getText();
        Helado h;
        try {
            // TODO add your handling code here:
            h = mh.pedirHelado(posicion);
            heladoDevuelto.setVisible(true);
            txtHelado.setText("Puede recoger su helado sabor " + h.getSabor() + " de tipo " + h.getTipo());
            if (h.getTipo().equalsIgnoreCase("tarrina")) {
                tipoHelado.setIcon(new ImageIcon(getClass().getResource("/resources/imgs/heladoTarrina.png")));
            } else if (h.getTipo().equalsIgnoreCase("palo")) {
                tipoHelado.setIcon(new ImageIcon(getClass().getResource("/resources/imgs/heladoPalo.png")));
            } else if (h.getTipo().equalsIgnoreCase("cucurucho")) {
                tipoHelado.setIcon(new ImageIcon(getClass().getResource("/resources/imgs/heladoCucurucho.png")));
            }
            txtCambio.setText(" Su cambio es: " + Utils.formatoDecimal(mh.getMonedero()) + "€");
            mh.setMonedero(0);
            refreshVerMonedero();
            rellenarTablaHelados();
        } catch (QuantityExceededException | NotValidPositionException | NotEnoughMoneyException ex) {
            ventanaError(ex.getMessage());
        } catch (Exception ex) {
            ventanaError("Ha ocurrido un error al pedir el helado.");
        }

    }//GEN-LAST:event_pedirHeladoActionPerformed

    private void informeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeVentasActionPerformed
        // TODO add your handling code here:
        DialogInformeVentas di = new DialogInformeVentas(this, true);
        di.setVisible(true);
    }//GEN-LAST:event_informeVentasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //cerrar();
        if (mh.getMonedero() > 0) {
            DialogCambioFinal dcf = new DialogCambioFinal(this, true);
            dcf.setVisible(true);
            System.exit(0);
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuReponerHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReponerHeladoActionPerformed
        // TODO add your handling code here:
        DialogReponerHelado drh = new DialogReponerHelado(this, true);
        drh.setVisible(true);
    }//GEN-LAST:event_jMenuReponerHeladoActionPerformed

    private void heladosOrderPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heladosOrderPrecioActionPerformed
        // TODO add your handling code here:
        ArrayList<Helado> listaHelados;

        DefaultTableModel m = (DefaultTableModel) this.tablaHelados.getModel();
        m.setRowCount(0);
        try {

            listaHelados = mh.getHeladosOrderByPrecio();
            for (Helado h : listaHelados) {
                Object[] tmp = {h.getPosicion(), h.getSabor(), h.getTipo(), Utils.formatoDecimal(h.getPrecio()) + "€", h.getCantidad()};
                m.addRow(tmp);
            }

        } catch (Exception ex) {
            ventanaError("Ha ocurrido un error al mostrar los helados.");
        }
    }//GEN-LAST:event_heladosOrderPrecioActionPerformed

    private void jMenuInsertarHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInsertarHeladoActionPerformed
        // TODO add your handling code here:
        DialogIntroducirHelado dih = new DialogIntroducirHelado(this, true);
        dih.setVisible(true);
    }//GEN-LAST:event_jMenuInsertarHeladoActionPerformed

    private void eliminarHeladoPosicionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarHeladoPosicionMenuActionPerformed
        DialogoEliminarHeladoPosicion dehp = new DialogoEliminarHeladoPosicion(this, true);
        dehp.setVisible(true);
    }//GEN-LAST:event_eliminarHeladoPosicionMenuActionPerformed

    private void jMenuCambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCambiarDatosActionPerformed
        // TODO add your handling code here:
        DialogCambiarDatos dcd = new DialogCambiarDatos(this, true);
        dcd.setVisible(true);
    }//GEN-LAST:event_jMenuCambiarDatosActionPerformed

    private void jMenuHeladoMasVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHeladoMasVendidoActionPerformed
        // TODO add your handling code here:
        try {

            masMenosVendido.setVisible(true);
        } catch (Exception ex) {
            ventanaError(ex.toString());
        }

    }//GEN-LAST:event_jMenuHeladoMasVendidoActionPerformed

    private void jButtonMasVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasVendidoActionPerformed
        // TODO add your handling code here:

        try {

            mostrarHeladoMasMenos.setText("El helado mas vendido es: " + mh.getHeladoMenosVendido());

        } catch (Exception ex) {
            ventanaError(ex.toString());
        }


    }//GEN-LAST:event_jButtonMasVendidoActionPerformed

    private void jButtonMenosVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosVendidoActionPerformed
        // TODO add your handling code here:

        try {

            mostrarHeladoMasMenos.setText("El helado mas vendido es: " + mh.getHeladoMasVendido());

        } catch (Exception ex) {
            ventanaError(ex.toString());
        }
    }//GEN-LAST:event_jButtonMenosVendidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exec().setVisible(true);
            }
        });
    }

    public void introducirPosicion(String posicion) {
        if (verPosicion.getText().length() < 2) {
            verPosicion.setText(verPosicion.getText() + posicion);
        }
    }

    public void rellenarTablaHelados() {
        ArrayList<Helado> listaHelados;

        DefaultTableModel m = (DefaultTableModel) this.tablaHelados.getModel();
        m.setRowCount(0);
        try {

            listaHelados = mh.getHelados();
            for (Helado h : listaHelados) {
                Object[] tmp = {h.getPosicion(), h.getSabor(), h.getTipo(), Utils.formatoDecimal(h.getPrecio()) + "€", h.getCantidad()};
                m.addRow(tmp);
            }

        } catch (Exception ex) {
            ventanaError("Ha ocurrido un error al mostrar los helados.");
        }
    }

    public void refreshVerMonedero() {
        this.verMonedero.setText(Utils.formatoDecimal(mh.getMonedero()) + "€");
    }

    public void ventanaError(String texto) {
        mensajeError.setText(texto);
        ventanaError.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPosicion;
    private javax.swing.JButton devolverDinero;
    private javax.swing.JDialog devuelto;
    private javax.swing.JMenuItem eliminarHeladoPosicionMenu;
    private javax.swing.JDialog heladoDevuelto;
    private javax.swing.JMenuItem heladosOrderPrecio;
    private javax.swing.JMenuItem informeVentas;
    private javax.swing.JButton introducirMonedas;
    private javax.swing.JButton jButtonMasVendido;
    private javax.swing.JButton jButtonMenosVendido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCambiarDatos;
    private javax.swing.JMenuItem jMenuHeladoMasVendido;
    private javax.swing.JMenuItem jMenuInsertarHelado;
    private javax.swing.JMenuItem jMenuReponerHelado;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDialog masMenosVendido;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JLabel mostrarHeladoMasMenos;
    private javax.swing.JButton pedirHelado;
    private javax.swing.JButton posicionCero;
    private javax.swing.JButton posicionCinco;
    private javax.swing.JButton posicionCuatro;
    private javax.swing.JButton posicionDos;
    private javax.swing.JButton posicionNueve;
    private javax.swing.JButton posicionOcho;
    private javax.swing.JButton posicionSeis;
    private javax.swing.JButton posicionSiete;
    private javax.swing.JButton posicionTres;
    private javax.swing.JButton posicionUno;
    private javax.swing.JTable tablaHelados;
    private javax.swing.JLabel tipoHelado;
    private javax.swing.JLabel txtCambio;
    private javax.swing.JLabel txtHelado;
    private javax.swing.JLabel txtUser;
    private javax.swing.JDialog ventanaError;
    private javax.swing.JTextField verMonedero;
    private javax.swing.JTextField verPosicion;
    // End of variables declaration//GEN-END:variables
    private MaquinaHelados mh = new MaquinaHelados();

    public MaquinaHelados getMh() {
        return mh;
    }
}
