/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;

import com.ejerciciosTrimestre.maquinaHeladosV7.biz.Helado;
import com.ejerciciosTrimestre.maquinaHeladosV7.biz.MaquinaHelados;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 *
 */
public class Exec extends javax.swing.JFrame {

    /**
     * Creates new form Exec
     */
    public Exec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devuelto = new javax.swing.JDialog();
        txtUser = new javax.swing.JLabel();
        introducirMonedas = new javax.swing.JButton();
        devolverDinero = new javax.swing.JButton();
        verMonedero = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaHelados = new javax.swing.JTable();

        devuelto.setResizable(false);

        txtUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout devueltoLayout = new javax.swing.GroupLayout(devuelto.getContentPane());
        devuelto.getContentPane().setLayout(devueltoLayout);
        devueltoLayout.setHorizontalGroup(
            devueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devueltoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        devueltoLayout.setVerticalGroup(
            devueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devueltoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        devuelto.setSize(500, 100);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        introducirMonedas.setText("Introducir monedas");
        introducirMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirMonedasActionPerformed(evt);
            }
        });

        devolverDinero.setText("D");
        devolverDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverDineroActionPerformed(evt);
            }
        });

        verMonedero.setEditable(false);
        verMonedero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verMonedero.setFocusable(false);

        tablaHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Sabor", "Tipo", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHelados.setColumnSelectionAllowed(true);
        tablaHelados.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaHelados);
        tablaHelados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(verMonedero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(devolverDinero)
                        .addGap(18, 18, 18)
                        .addComponent(introducirMonedas)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introducirMonedas)
                    .addComponent(devolverDinero)
                    .addComponent(verMonedero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(206, 206, 206))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introducirMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirMonedasActionPerformed
        // TODO add your handling code here:
        // TODO hacer que la ventana actualice el monedero en tiempo real:
        DialogMonedas dm = new DialogMonedas(this, true);
        dm.setVisible(true);
        mh = dm.getAux();
        verMonedero.setText(Double.toString(mh.getMonedero()) + "€");
    }//GEN-LAST:event_introducirMonedasActionPerformed

    private void devolverDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverDineroActionPerformed
        // TODO add your handling code here:
        devuelto.setVisible(true);
        txtUser.setText("Su dinero le ha sido duevuelto " + Double.toString(mh.getMonedero()) + "€");
        mh.setMonedero(0);
        verMonedero.setText(Double.toString(mh.getMonedero()) + "€");
    }//GEN-LAST:event_devolverDineroActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        if (verMonedero.isVisible()) {
            verMonedero.setText(Double.toString(mh.getMonedero()) + "€");
        }
        ArrayList<Helado> listaHelados;
        DefaultTableModel m = (DefaultTableModel) this.tablaHelados.getModel();
        m.setRowCount(0);
        try {
            listaHelados = mh.getHelados();
            for (Helado h : listaHelados) {
                Object[] tmp = {h.getPosicion(), h.getSabor(), h.getTipo(), h.getPrecio(), h.getCantidad()};
                m.addRow(tmp);
            }
        } catch (Exception ex) {
            Logger.getLogger(Exec.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devolverDinero;
    private javax.swing.JDialog devuelto;
    private javax.swing.JButton introducirMonedas;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaHelados;
    private javax.swing.JLabel txtUser;
    private javax.swing.JTextField verMonedero;
    // End of variables declaration//GEN-END:variables
    private MaquinaHelados mh = new MaquinaHelados();
}
