/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ejerciciosTrimestre.maquinaHeladosV7.gui;

import com.ejerciciosTrimestre.maquinaHeladosV7.biz.Helado;
import com.ejerciciosTrimestre.maquinaHeladosV7.biz.MaquinaHelados;
import com.ejerciciosTrimestre.maquinaHeladosV7.exceptions.NotEnoughMoneyException;
import com.ejerciciosTrimestre.maquinaHeladosV7.exceptions.NotValidPositionException;
import com.ejerciciosTrimestre.maquinaHeladosV7.exceptions.QuantityExceededException;
import com.ejerciciosTrimestre.maquinaHeladosV7.utils.Utils;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 *
 */
public class Exec extends javax.swing.JFrame {

    /**
     * Creates new form Exec
     */
    public Exec() {
        initComponents();
        tablaHelados.getTableHeader().setDefaultRenderer(new Utils.CentrarTitulosColumnas());
        for (int i = 0; i < tablaHelados.getColumnCount(); i++) {
            tablaHelados.getColumnModel().getColumn(i).setCellRenderer(new Utils.CentrarTexto());
        }
    }

    private class CentrarTexto extends Utils.CentrarTexto {

        public CentrarTexto() {
            super();
        }
    }

    private class CentrarTitulosColumnas extends Utils.CentrarTitulosColumnas {

        public CentrarTitulosColumnas() {
            super();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devuelto = new javax.swing.JDialog();
        txtUser = new javax.swing.JLabel();
        heladoDevuelto = new javax.swing.JDialog();
        txtHelado = new javax.swing.JLabel();
        introducirMonedas = new javax.swing.JButton();
        devolverDinero = new javax.swing.JButton();
        verMonedero = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaHelados = new javax.swing.JTable();
        verPosicion = new javax.swing.JTextField();
        posicionDos = new javax.swing.JButton();
        posicionTres = new javax.swing.JButton();
        borrarPosicion = new javax.swing.JButton();
        posicionCuatro = new javax.swing.JButton();
        posicionCinco = new javax.swing.JButton();
        posicionSeis = new javax.swing.JButton();
        posicionSiete = new javax.swing.JButton();
        posicionOcho = new javax.swing.JButton();
        posicionNueve = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        posicionCero = new javax.swing.JButton();
        posicionUno = new javax.swing.JButton();
        pedirHelado = new javax.swing.JButton();
        txtError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        informeVentas = new javax.swing.JMenuItem();

        devuelto.setResizable(false);

        txtUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout devueltoLayout = new javax.swing.GroupLayout(devuelto.getContentPane());
        devuelto.getContentPane().setLayout(devueltoLayout);
        devueltoLayout.setHorizontalGroup(
            devueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devueltoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        devueltoLayout.setVerticalGroup(
            devueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devueltoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        devuelto.setSize(500, 100);

        heladoDevuelto.setResizable(false);

        txtHelado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout heladoDevueltoLayout = new javax.swing.GroupLayout(heladoDevuelto.getContentPane());
        heladoDevuelto.getContentPane().setLayout(heladoDevueltoLayout);
        heladoDevueltoLayout.setHorizontalGroup(
            heladoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heladoDevueltoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        heladoDevueltoLayout.setVerticalGroup(
            heladoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heladoDevueltoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        heladoDevuelto.setSize(700, 200);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        introducirMonedas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        introducirMonedas.setText("Introducir monedas");
        introducirMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirMonedasActionPerformed(evt);
            }
        });

        devolverDinero.setText("D");
        devolverDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverDineroActionPerformed(evt);
            }
        });

        verMonedero.setEditable(false);
        verMonedero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verMonedero.setFocusable(false);

        tablaHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Sabor", "Tipo", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHelados.setColumnSelectionAllowed(true);
        tablaHelados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaHelados.setShowGrid(false);
        tablaHelados.setShowHorizontalLines(true);
        tablaHelados.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaHelados);
        tablaHelados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        verPosicion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verPosicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verPosicionKeyTyped(evt);
            }
        });

        posicionDos.setText("2");
        posicionDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionDosActionPerformed(evt);
            }
        });

        posicionTres.setText("3");
        posicionTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionTresActionPerformed(evt);
            }
        });

        borrarPosicion.setText("D");
        borrarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPosicionActionPerformed(evt);
            }
        });

        posicionCuatro.setText("4");
        posicionCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCuatroActionPerformed(evt);
            }
        });

        posicionCinco.setText("5");
        posicionCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCincoActionPerformed(evt);
            }
        });

        posicionSeis.setText("6");
        posicionSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSeisActionPerformed(evt);
            }
        });

        posicionSiete.setText("7");
        posicionSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSieteActionPerformed(evt);
            }
        });

        posicionOcho.setText("8");
        posicionOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionOchoActionPerformed(evt);
            }
        });

        posicionNueve.setText("9");
        posicionNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionNueveActionPerformed(evt);
            }
        });

        posicionCero.setText("0");
        posicionCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionCeroActionPerformed(evt);
            }
        });

        posicionUno.setText("1");
        posicionUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionUnoActionPerformed(evt);
            }
        });

        pedirHelado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        pedirHelado.setText("Pedir helado");
        pedirHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirHeladoActionPerformed(evt);
            }
        });

        txtError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenu1.setText("Menu");

        informeVentas.setText("Informe de ventas");
        informeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeVentasActionPerformed(evt);
            }
        });
        jMenu1.add(informeVentas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(verMonedero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(devolverDinero)
                        .addGap(18, 18, 18)
                        .addComponent(introducirMonedas)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(verPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(borrarPosicion)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(posicionCinco)
                                    .addGap(18, 18, 18)
                                    .addComponent(posicionSeis)
                                    .addGap(18, 18, 18)
                                    .addComponent(posicionSiete)
                                    .addGap(18, 18, 18)
                                    .addComponent(posicionOcho)
                                    .addGap(18, 18, 18)
                                    .addComponent(posicionNueve))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(posicionCero)
                                    .addGap(18, 18, 18)
                                    .addComponent(posicionUno)
                                    .addGap(18, 18, 18)
                                    .addComponent(posicionDos)
                                    .addGap(18, 18, 18)
                                    .addComponent(posicionTres)
                                    .addGap(18, 18, 18)
                                    .addComponent(posicionCuatro))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pedirHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introducirMonedas)
                    .addComponent(devolverDinero)
                    .addComponent(verMonedero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pedirHelado)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(posicionCero)
                            .addComponent(posicionUno)
                            .addComponent(posicionDos)
                            .addComponent(posicionTres)
                            .addComponent(posicionCuatro))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(posicionCinco)
                            .addComponent(posicionSeis)
                            .addComponent(posicionSiete)
                            .addComponent(posicionOcho)
                            .addComponent(posicionNueve)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrarPosicion))
                        .addGap(22, 22, 22)))
                .addGap(31, 31, 31)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        txtError.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introducirMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirMonedasActionPerformed
        // TODO add your handling code here:
        // TODO hacer que la ventana actualice el monedero en tiempo real:
        DialogMonedas dm = new DialogMonedas(this, true);
        dm.setVisible(true);
        mh.setMonedero(mh.getMonedero() + dm.getAux().getMonedero());
        verMonedero.setText(Double.toString(mh.getMonedero()) + "€");
    }//GEN-LAST:event_introducirMonedasActionPerformed

    private void devolverDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverDineroActionPerformed
        // TODO add your handling code here:
        devuelto.setVisible(true);
        txtUser.setText("Su dinero le ha sido duevuelto " + Double.toString(mh.getMonedero()) + "€");
        mh.setMonedero(0);
        verMonedero.setText(Double.toString(mh.getMonedero()) + "€");
    }//GEN-LAST:event_devolverDineroActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        verMonedero.setText(Double.toString(mh.getMonedero()) + "€");
        rellenarTablaHelados();
    }//GEN-LAST:event_formComponentShown

    private void verPosicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verPosicionKeyTyped
        // TODO add your handling code here:
        if (verPosicion.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_verPosicionKeyTyped

    private void posicionDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionDosActionPerformed
        // TODO add your handling code here:
        introducirPosicion("2");
    }//GEN-LAST:event_posicionDosActionPerformed

    private void posicionTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionTresActionPerformed
        // TODO add your handling code here:
        introducirPosicion("3");
    }//GEN-LAST:event_posicionTresActionPerformed

    private void borrarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPosicionActionPerformed
        // TODO add your handling code here:
        verPosicion.setText("");
    }//GEN-LAST:event_borrarPosicionActionPerformed

    private void posicionCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCuatroActionPerformed
        // TODO add your handling code here:
        introducirPosicion("4");
    }//GEN-LAST:event_posicionCuatroActionPerformed

    private void posicionCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCincoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("5");
    }//GEN-LAST:event_posicionCincoActionPerformed

    private void posicionSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSeisActionPerformed
        // TODO add your handling code here:
        introducirPosicion("6");
    }//GEN-LAST:event_posicionSeisActionPerformed

    private void posicionSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSieteActionPerformed
        // TODO add your handling code here:
        introducirPosicion("7");
    }//GEN-LAST:event_posicionSieteActionPerformed

    private void posicionOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionOchoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("8");
    }//GEN-LAST:event_posicionOchoActionPerformed

    private void posicionNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionNueveActionPerformed
        // TODO add your handling code here:
        introducirPosicion("9");
    }//GEN-LAST:event_posicionNueveActionPerformed

    private void posicionCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionCeroActionPerformed
        // TODO add your handling code here:
        introducirPosicion("0");
    }//GEN-LAST:event_posicionCeroActionPerformed

    private void posicionUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionUnoActionPerformed
        // TODO add your handling code here:
        introducirPosicion("1");
    }//GEN-LAST:event_posicionUnoActionPerformed

    private void pedirHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirHeladoActionPerformed
        String posicion = verPosicion.getText();
        Helado h;
        try {
            // TODO add your handling code here:
            h = mh.pedirHelado(posicion);
            heladoDevuelto.setVisible(true);
            txtHelado.setText("Puede recoger su helado sabor " + h.getSabor() + " de tipo " + h.getTipo() + " Su cambio es: " + mh.getMonedero());
            mh.setMonedero(0);
            verMonedero.setText(Double.toString(mh.getMonedero()) + "€");
            rellenarTablaHelados();
        } catch (QuantityExceededException ex) {
            txtError.setText(ex.getMessage());
            txtError.setVisible(true);
        } catch (NotValidPositionException ex) {
            txtError.setText(ex.getMessage());
            txtError.setVisible(true);
        } catch (NotEnoughMoneyException ex) {
            txtError.setText(ex.getMessage());
            txtError.setVisible(true);
        } catch (Exception ex) {
            txtError.setText("Ha ocurrido un error al pedir el helado.");
            txtError.setVisible(true);
        }

    }//GEN-LAST:event_pedirHeladoActionPerformed

    private void informeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeVentasActionPerformed
        // TODO add your handling code here:
        DialogInformeVentas di = new DialogInformeVentas(this, true);
        di.setVisible(true);
    }//GEN-LAST:event_informeVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exec().setVisible(true);
            }
        });
    }

    public void introducirPosicion(String posicion) {
        if (verPosicion.getText().length() < 2) {
            verPosicion.setText(verPosicion.getText() + posicion);
        }
    }

    public void rellenarTablaHelados() {
        ArrayList<Helado> listaHelados;

        DefaultTableModel m = (DefaultTableModel) this.tablaHelados.getModel();
        m.setRowCount(0);
        try {

            listaHelados = mh.getHelados();
            for (Helado h : listaHelados) {
                Object[] tmp = {h.getPosicion(), h.getSabor(), h.getTipo(), h.getPrecio(), h.getCantidad()};
                m.addRow(tmp);
            }

        } catch (Exception ex) {
            txtError.setText("Ha ocurrido un error al mostrar los helados.");
            txtError.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPosicion;
    private javax.swing.JButton devolverDinero;
    private javax.swing.JDialog devuelto;
    private javax.swing.JDialog heladoDevuelto;
    private javax.swing.JMenuItem informeVentas;
    private javax.swing.JButton introducirMonedas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton pedirHelado;
    private javax.swing.JButton posicionCero;
    private javax.swing.JButton posicionCinco;
    private javax.swing.JButton posicionCuatro;
    private javax.swing.JButton posicionDos;
    private javax.swing.JButton posicionNueve;
    private javax.swing.JButton posicionOcho;
    private javax.swing.JButton posicionSeis;
    private javax.swing.JButton posicionSiete;
    private javax.swing.JButton posicionTres;
    private javax.swing.JButton posicionUno;
    private javax.swing.JTable tablaHelados;
    private javax.swing.JLabel txtError;
    private javax.swing.JLabel txtHelado;
    private javax.swing.JLabel txtUser;
    private javax.swing.JTextField verMonedero;
    private javax.swing.JTextField verPosicion;
    // End of variables declaration//GEN-END:variables
    private MaquinaHelados mh = new MaquinaHelados();
}
